name: Node.js CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Linter (ESLint)
      run: npm lint
    - name: Formatter (Prettier)
      run: npm prettier 
    - name: Test (Jest)
      run: npm test
      with:
        CI: true
        run: npm test
    - run: npm run build --if-present
